### ISSUE TITLE
[SUGGESTION] optimize the server part

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-banking#70]
Why does the qb-banking part of the server.lua use a while loop? If there are a lot of events running, it will cause a lot of resource utilization in the svgui.

![image](https://user-images.githubusercontent.com/108535266/179499386-59bb2cb7-f386-41f8-8148-926fbf16b44f.png)

If an Event is called repeatedly it causes the while loop to run all the time and increments with the event. I'm worried that it will use too much server resources.
![image](https://user-images.githubusercontent.com/108535266/179500103-286151d2-3ab4-4bd4-8fd4-2dfd56c24a71.png)

**Comment by XLightDev** [comment]
Should I use this instead?

if bank == nil then
    return
end

if savings == nil then
    return
end

**Comment by XLightDev** [comment]
And I turn off the while loop because there is no notification of discord logs, savings Deposit and savings Withdraw.

**Comment by JericoFX** [comment]
What I see, in that resource the while is just to ensure that the player is not nil so prevent some errors, if you use the if as you suggested, the event will never reach the end and the nui will get stuck or a timeout because will not have no return on the callback, and the while will only run on the trigger callback.

**Comment by JericoFX** [comment]
> What I see, in that resource the while is just to ensure that the player is not nil so prevent some errors, if you use the if as you suggested, the event will never reach the end and the nui will get stuck or a timeout because will not have no return on the callback, and the while will only run on the trigger callback. 

At leas the first one, the others while aren't necessary

**Comment by XLightDev** [comment]
I replaced while with if xPlayer == nil then return end , I think it's better not having a loop iterates all the time.

**Comment by JericoFX** [comment]
What I see, in that resource the while is just to ensure that the player is not nil so prevent some errors, if you use the if as you suggested, the event will never reach the end and the nui will get stuck or a timeout because will not have no return on the callback, and the while will only run on the trigger callback. It will iterate only until the source isn't nil maybe half of a second

**Comment by JericoFX** [comment]
> I replaced while with if xPlayer == nil then return end , I think it's better not having a loop iterates all the time.

It will iterate half of a second or less because the source is already provided, if you trigger a server event the source will be always passed
